version: "3"
services:
  postgres:
    image: postgres
    restart: always
    environment:
      POSTGRES_DB: mlflow
      POSTGRES_USER: super_user
      POSTGRES_PASSWORD: su_password

  mlflow:
    build:
      context: .
      dockerfile: "${DOCKERFILE:-Dockerfile}"
    depends_on:
      - postgres
    expose:
      - "5000"
    ports:
      - "5000:5000"
    env_file:
      - .env
    command: >
      mlflow server
      --host 0.0.0.0
      --port 5000
      --backend-store-uri postgresql://super_user:su_password@postgres:5432/mlflow
      --artifacts-destination s3://jeongmin-mlflow-bucket
      --serve-artifacts
      --default-artifact-root s3://jeongmin-mlflow-bucket